apiVersion: gitops.kluctl.io/v1beta1
kind: KluctlDeployment
metadata:
  name: demo-app
  namespace: kluctl-gitops
spec:
  interval: 5m
  source:
    git:
      url: https://github.com/vlad-yarko/my-ci-cd-app.git
      path: k8s/application
  target: staging
  context: default
  # let it automatically clean up orphan KluctlDeployment resources
  prune: true
  delete: true
