backend:
  deployment:
    image: vladyslavyarko/ci-cd-backend-image 
    version: 1 # staging_services/backend

database:
  migrationJobImage: vladyslavyarko/ci-cd-database-image 
  version: 1.0.2-0004-g2a425f7 # staging_services/database

frontend:
  deployment:
    image: vladyslavyarko/ci-cd-frontend-image
    version: 1 # staging_services/frontend
