backend:
  deployment:
    image: vladyslavyarko/ci-cd-backend-image 
    version: 1.0.10-0027-g9adae51 # staging_services/backend

database:
  migrationJobImage: vladyslavyarko/ci-cd-database-image 
  version: 2.1.1-0000-g8046ea4 # staging_services/database

frontend:
  deployment:
    image: vladyslavyarko/ci-cd-frontend-image
    version: b2d1e42-0000-gb2d1e42 # staging_services/frontend
