backend:
  deployment:
    image: vladyslavyarko/ci-cd-backend-image 
    version: 1.0.10-0027-g9adae51 # staging_services/backend

database:
  migrationJobImage: vladyslavyarko/ci-cd-database-image 
  version: 2.1.0-0005-gda60034 # staging_services/database

frontend:
  deployment:
    image: vladyslavyarko/ci-cd-frontend-image
    version: 9adae51-0000-g9adae51 # staging_services/frontend
