backend:
  deployment:
    image: vladyslavyarko/ci-cd-backend-image 
    version: 1.0.51-0000-g534351c # staging_services/backend

database:
  migrationJobImage: vladyslavyarko/ci-cd-database-image 
  version: 2.1.1-0047-gb7954be # staging_services/database

frontend:
  deployment:
    image: vladyslavyarko/ci-cd-frontend-image
    version: 1.0.51-0000-g91f59c1 # staging_services/frontend
