backend:
  deployment:
    image: vladyslavyarko/ci-cd-backend-image 
    version: 1.0.10-0018-gc5b6ec3 # staging_services/backend

database:
  migrationJobImage: vladyslavyarko/ci-cd-database-image 
  version: 1.0.6-0001-gc95bc0f # staging_services/database

frontend:
  deployment:
    image: vladyslavyarko/ci-cd-frontend-image
    version: c5b6ec3-0000-gc5b6ec3 # staging_services/frontend
