backend:
  deployment:
    image: vladyslavyarko/ci-cd-backend-image 
    version: 1.0.10-0027-g9adae51 # staging_services/backend

database:
  migrationJobImage: vladyslavyarko/ci-cd-database-image 
  version: 2.1.1-0011-g5f2a8d2 # staging_services/database

frontend:
  deployment:
    image: vladyslavyarko/ci-cd-frontend-image
    version: 2.0.1-0000-g706c4e4 # staging_services/frontend
