sharedNamespace: {{ namespaces.application.name }}
# applicationHost: my-kubernetes.chickenkiller.com
applicationHost: kubernetes-yep.duckdns.org


backend:
  middleware:
    name: backend-middleware
    prefix: /api

  deployment:
    name: backend-deployment
    podName: backend-pod
    replicas: {{ replica }}
    containerName: backend-container
    # image: ghcr.io/vlad-yarko/my-kubernetes-backend:1.0.0
    image: {{ backend.deployment.image }}
    version: {{ backend.deployment.version }}
    containerPort: 8000

  service:
    name: backend-service
    port: 8000

  ingressRoute:
    name: backend-ingressroute
  
  secret: {{ args.environment }}


database:
  secretName: database-secret

secret_tls:
  name: secret-tls

middleware_tls:
  name: middleware-tls

harborSecret:
  name: harbor-secret

environment: {{ args.environment }}
