name: Export GitHub Action Timing Data

on:
  workflow_run:
    workflows:
      - "Build & Push"
      - "Tests"
      - "GitOps CD"
      - "Close Stale Issues and PRs"
    #   - "Release Please"
    types: [completed]

jobs:
  export-otel-trace:
    name: OpenTelemetry Export Trace
    runs-on: ubuntu-24.04
    steps:
      - name: Export Workflow Trace
        uses: corentinmusard/otel-cicd-action@769ccb38830ff3d1600ffb2f35ba9da6724e6b3e # v2.2.4
        with:
          otlpEndpoint: grpc://api.honeycomb.io:443/
          # Formatted as x-honeycomb-team=YOUR_API_KEY
          otlpHeaders: ${{ secrets.HONEYCOMB_OTLP_HEADERS }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          runId: ${{ github.event.workflow_run.id }}
